#!/usr/bin/env python3
"""
v7.1-F — Transform intermediate spec to full HA automation spec.

Reads from PENDING_SPEC_PATH and writes back in canonical HA format.
No arguments - reads and overwrites the file.

Supports three input formats:
  1. Raw fields (from ai_task via JSON): has key "trigger_type", valid JSON
  2. Raw fields (from ai_task via YAML-style): HA renders MappingProxy as YAML
     Ex: {alias: Turn on AC, trigger_type: time, trigger_config: {...}}
  3. Direct HA spec (from legacy conversation.process): has "trigger" as list
"""
import sys
import os
import json
import uuid
import ast
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib.memory import save_json
from permear_config import PENDING_SPEC_PATH


def parse_file_content(raw):
    """Try JSON first; fallback to YAML-style (generated by HA for MappingProxy)."""
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass
    try:
        import yaml
        return yaml.safe_load(raw)
    except Exception:
        return None


def build_trigger_from_fields(trigger_type, trigger_config_raw):
    """Accept trigger_config as dict (YAML-parsed) or string (JSON or Python repr)."""
    if isinstance(trigger_config_raw, dict):
        cfg = trigger_config_raw
    elif isinstance(trigger_config_raw, str):
        config_str = trigger_config_raw.strip()
        if not config_str or config_str.lower() in ("null", "none", "{}", ""):
            return None
        try:
            cfg = json.loads(config_str)
        except json.JSONDecodeError:
            try:
                cfg = ast.literal_eval(config_str)
            except (ValueError, SyntaxError):
                return None
    else:
        return None

    if not isinstance(cfg, dict):
        return None
    if "platform" not in cfg:
        cfg["platform"] = trigger_type
    return [cfg]


def build_action_from_fields(service, entity_id):
    if not service or not entity_id:
        return None
    return [{"service": service, "target": {"entity_id": entity_id}}]


def main():
    if not os.path.exists(PENDING_SPEC_PATH):
        print("ERROR: pending_auto_spec.json not found")
        sys.exit(1)

    with open(PENDING_SPEC_PATH, "r") as f:
        raw = f.read().strip()

    if not raw:
        print("ERROR: pending_auto_spec.json empty")
        sys.exit(1)

    data = parse_file_content(raw)
    if data is None or not isinstance(data, dict):
        print("ERROR: invalid format in pending_auto_spec.json (neither JSON nor YAML)")
        sys.exit(1)

    # Format 1 & 2: raw fields from ai_task.generate_data (JSON or YAML-style)
    if "trigger_type" in data:
        alias = str(data.get("alias", "")).strip()
        trigger_type = str(data.get("trigger_type", "time"))
        trigger_config_raw = data.get("trigger_config", "")
        action_service = str(data.get("action_service", ""))
        action_entity = str(data.get("action_entity", ""))

        if not alias:
            print("ERROR: empty alias in raw fields")
            sys.exit(1)

        trigger = build_trigger_from_fields(trigger_type, trigger_config_raw)
        if not trigger:
            tc_repr = str(trigger_config_raw)[:80]
            print(f"ERROR: invalid trigger. type='{trigger_type}' config='{tc_repr}'")
            sys.exit(1)

        action = build_action_from_fields(action_service, action_entity)
        if not action:
            print(f"ERROR: invalid action. service='{action_service}' entity='{action_entity}'")
            sys.exit(1)

        spec = {
            "id": f"agent_auto_{uuid.uuid4().hex[:8]}",
            "alias": alias,
            "trigger": trigger,
            "action": action,
            "mode": "single",
            "initial_state": "on",
        }
        if data.get("_condition_note"):
            spec["_condition_note"] = str(data["_condition_note"])

    # Format 3: direct HA spec (from legacy conversation.process)
    elif isinstance(data.get("trigger"), list):
        spec = data
        if not spec.get("id"):
            spec["id"] = f"agent_auto_{uuid.uuid4().hex[:8]}"
        spec.setdefault("mode", "single")
        spec.setdefault("initial_state", "on")

    else:
        print("ERROR: unknown format (neither trigger_type nor trigger as list)")
        sys.exit(1)

    save_json(PENDING_SPEC_PATH, spec)
    print(f"Spec built: '{spec.get('alias', '?')}' (id={spec.get('id', '?')})")


if __name__ == "__main__":
    main()
